### ISSUE TITLE
Question on key name

### ISSUE THREAD

**Issue by zjyonline** [sgtram/apollo-server-redis-cache#2]
Hi，I'm glad to find you save `graphql cache` problem, but I have a question about redis key name you define, why add `structureVersion` in key name ?

**Comment by bderen** [comment]
Hi, in case something wrong with the cache you can change cache key by setting new structureVersion, so it will use a new one and old cache will just expire.
Initially, I was using package version as a key prefix but we want to keep cache key the same every time we release to production. And only change it when we really have to.

**Comment by zjyonline** [comment]
All right ,but I really think that `structureVersion ` if it can be define in my own config maybe better ?  ranther than in `package.json` file ?

**Comment by bderen** [comment]
yes you can set your key in the initialization of the cache 
```
const cahce = new apolloServerRedisCache({ cache: true, key: 'asrc'})
```

**Comment by zjyonline** [comment]
I know it , but I dislike to use `structureVersion` in redis key name . There is a risk that if you change `structureVersion` in `package.json` file, my new server use `npm i` and get new  `structureVersion` 
 word. that's a big problem.

**Comment by bderen** [comment]
Could you please explain why this is a big problem?
And please if you want you can always send PR
